# Generated by Django 4.2.25 on 2025-10-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, choices=[(None, '-')], max_length=100, null=True, verbose_name='Страна'),
        ),
    ]
