# Generated by Django 4.2.24 on 2025-09-30 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_status_friend_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='follower_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_for', to=settings.AUTH_USER_MODEL, verbose_name='Подписан на...'),
        ),
    ]
