# Generated by Django 4.2.24 on 2025-09-30 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_follower_follower_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='follower_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_for', to=settings.AUTH_USER_MODEL, verbose_name='Подписан на ...'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='users_friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_friend', to=settings.AUTH_USER_MODEL, verbose_name='В дружбе с ...'),
        ),
    ]
