# Generated by Django 4.2.24 on 2025-09-30 21:30

import Users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_follower_follower_for_alter_follower_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=Users.models.CityField(blank=True, max_length=100, verbose_name='Город'),
        ),
    ]
