# Generated by Django 4.2.25 on 2025-10-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование задачи'),
        ),
    ]
