# Generated by Django 4.2.24 on 2025-10-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100, verbose_name='Наименование приложения')),
                ('emblem', models.CharField(max_length=10, verbose_name='Ярлык')),
                ('description', models.TextField(max_length=500, verbose_name='Описание приложения')),
                ('url', models.CharField(max_length=1000, verbose_name='Url-адрес приложения')),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
            },
        ),
    ]
