# Generated by Django 4.2.25 on 2025-10-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='base_url',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Url-адрес микросервиса'),
        ),
    ]
